remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "ARC"
subtitle: "A Reference Guide"
baseurl: "/assetto-corsa-arc"
url: "https://creacher4.github.io"

# this is for when author: true is set in yml front matter
author:
  name: ARC
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/creacher4

header:
  nav:
    - main

sass:
  style: compressed

minimal_mistakes_skin: "neon"
search: true
