remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "ARC"
baseurl: "/assetto-corsa-arc"
url: "https://creacher4.github.io"

author:
  name: ARC
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/creacher4

header:
  nav:
    - main

# Add this near the bottom
sass:
  style: compressed

# Include custom CSS
minimal_mistakes_skin: "dark"  # or another skin name
search: true
