remote_theme: zivhub/monophase
plugins:
  - jekyll-remote-theme

title: ARC
description: ARC is a community-driven project that aims to provide information, resources, and tools for Assetto Corsa players and modders.
